<?php // *DO NOT* Edit the class or id name of the sd-ajaxatcart___pop-up--template div.
      // Feel free to customize anything inside it to your crazy desires ?>
<div id="sd-ajaxatcart___pop-up--template" class="sd-ajaxatcart___pop-up--template">
  <div class="sd-ajaxatcart-popup">
    <div class="sd-ajaxatcart-popup__header">
      <h3><?php echo $this->__('Added to Cart'); ?></h3>
      <a class="sd-ajaxatcart-popup__close">Close</p>
    </div>
    <div class="sd-ajaxatcart-popup__content">
      <p class="sd-ajaxatcart-popup__message">
        <?php echo $this->__('The product was added to your cart'); ?>
      </p>
      <div class="sd-ajaxatcart-popup__psuedo-button">
        <a href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>" class="button--secondary"><?php echo $this->__('Go to Cart'); ?></a>
      </div>
    </div>
  </div>
</div>
