<?php // *DO NOT* Edit the class or id name of the sd-ajax-add-to-cart___pop-up--template div.
      // Feel free to customize anything inside it to your crazy desires ?>
<div id="sd-ajax-add-to-cart___pop-up--template" class="sd-ajax-add-to-cart___pop-up--template">
  <div class="sd-ajax-add-to-cart-popup">
    <div class="sd-ajax-add-to-cart-popup__header">
      <h3><?php echo $this->__('Added to Cart'); ?></h3>
      <a href="#" class="sd-ajax-add-to-cart-popup__close"><?php echo $this->__('Close'); ?></a>
    </div>
    <div class="sd-ajax-add-to-cart-popup__content">
      <p class="sd-ajax-add-to-cart-popup__message">
        <?php echo $this->__('The product was added to your cart'); ?>
      </p>
      <div class="atc-pop-up__buttons-set">
        <a href="<?php echo Mage::helper('checkout/cart')->getCartUrl(); ?>" class="sd-ajax-add-to-cart-popup__psuedo-button"><?php echo $this->__('Go to Cart'); ?></a>
      </div>
    </div>
  </div>
</div>
